name: Zesty Cloud
favicon: null
layout_spectrum: 0.46987146604806185
typography_spectrum: 0.8683080491609871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6033510977867991
  lightness: 0.599329388467595
  saturation: 0.895822822349146
  rhythmicContrast: 0.6730552762746811
purpose: []
